---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator
policyDefaults:
  namespace: bry-tam-policies-qa
  remediationAction: inform
  ## turn off the default compliance annotations
  categories: []
  controls: []
  standards: []
  policySets:
    - cluster-version
placementBindingDefaults:
  name: "cluster-version-binding"

policies:
  - name: api-deprecated-ack
    remediationAction: enforce
    manifests:
      - path: admin-acks-configmap.yml

  - name: ocp-upgrade
    remediationAction: enforce
    dependencies:
      - name: "api-deprecated-ack"
        compliance: "Compliant"
    manifests:
      - path: clusterversion.yml

policySets:
  - name: cluster-version
    placement:
      placementName: "env-bound-placement"